name: app_gestion_stage
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  flutter_bloc: ^9.1.1
  xml2json: ^6.2.0
  http: ^1.1.0
  url_launcher: ^6.3.1
  flutter_local_notifications: ^19.2.1
  firebase_messaging: ^15.2.6
  syncfusion_flutter_pdf: ^29.2.10
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lyceelogo.png
    - assets/lyceelogoWHITE.png
    - assets/app_icon.png
    - assets/ministereEducNationale.png
    - assets/pfmpPdf.pdf
    - assets/mentionLegal.txt
